// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfsBVHPo5EqnbJcIlzGCSZmULIZSdYZVI',
    appId: '1:269690780377:web:7b6b3d52cf8082383c9cc8',
    messagingSenderId: '269690780377',
    projectId: 'atbupq',
    authDomain: 'atbupq.firebaseapp.com',
    storageBucket: 'atbupq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVDXk5ndYMheUJhgdjktOgkTKE07_foGw',
    appId: '1:269690780377:android:72b0f8f70fb42aaf3c9cc8',
    messagingSenderId: '269690780377',
    projectId: 'atbupq',
    storageBucket: 'atbupq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr_iB2WiFpxoGnBRnygux_rxRDAW0NS0U',
    appId: '1:269690780377:ios:5f5d95f5888bcba13c9cc8',
    messagingSenderId: '269690780377',
    projectId: 'atbupq',
    storageBucket: 'atbupq.appspot.com',
    iosBundleId: 'com.example.atbuPq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr_iB2WiFpxoGnBRnygux_rxRDAW0NS0U',
    appId: '1:269690780377:ios:3cf6499aac8241e33c9cc8',
    messagingSenderId: '269690780377',
    projectId: 'atbupq',
    storageBucket: 'atbupq.appspot.com',
    iosBundleId: 'com.example.atbuPq.RunnerTests',
  );
}
